CREATE ROLE VIEWER;
CREATE ROLE DATA_ENG;
CREATE ROLE TEAM1_ENG;
CREATE ROLE TEAM2_ENG;

GRANT ROLE TEAM1_ENG TO ROLE DATA_ENG;
GRANT ROLE TEAM2_ENG TO ROLE DATA_ENG;

DROP USER datauser;


CREATE USER datauser
  PASSWORD='wUzg6WiTpNX@z@*pADZB3Wwg'
  LOGIN_NAME='datauser'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE='DW_INTERACTIVE_WH'
  DEFAULT_ROLE='DATA_ENG'
;

GRANT ROLE DATA_ENG TO USER datauser;
GRANT ROLE VIEWER TO USER datauser;

DROP USER team1user;

CREATE USER team1user
  PASSWORD='VtzBmfaN-k6Wv3fodBvh!znD'
  LOGIN_NAME='team1user'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE='DW_INTERACTIVE_WH'
  DEFAULT_ROLE='TEAM1_ENG'
;

GRANT ROLE TEAM1_ENG TO USER team1user;
GRANT ROLE VIEWER TO USER team1user;

DROP USER team2user;

CREATE USER team2user
  PASSWORD='-d.nAp.wkwccj6LY3DNF@u3i'
  LOGIN_NAME='team2user'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE='DW_INTERACTIVE_WH'
  DEFAULT_ROLE='TEAM2_ENG'
;

GRANT ROLE TEAM2_ENG TO USER team2user;
GRANT ROLE VIEWER TO USER team2user;

CREATE ROLE SCHEMACHANGE_DATA;
CREATE ROLE SCHEMACHANGE_TEAM1;
CREATE ROLE SCHEMACHANGE_TEAM2;
CREATE ROLE SCHEMACHANGE_DEV;

GRANT ROLE SCHEMACHANGE_TEAM1 TO ROLE SCHEMACHANGE_DATA;
GRANT ROLE SCHEMACHANGE_TEAM2 TO ROLE SCHEMACHANGE_DATA;

DROP USER SCHEMACHANGEDATA;
CREATE USER SCHEMACHANGEDATA
  PASSWORD='PcUGRL_@i2*r.Km7s8g8FUFQ'
  LOGIN_NAME='schemachangedata'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE='DW_INTERACTIVE_WH'
  DEFAULT_ROLE='SCHEMACHANGE_DATA'
;

GRANT ROLE SCHEMACHANGE_DATA TO USER SCHEMACHANGEDATA;

DROP USER SCHEMACHANGETEAM1;
CREATE USER SCHEMACHANGETEAM1
  PASSWORD='do8666vV!UnhFDzFW!qFoozb'
  LOGIN_NAME='schemachangeteam1'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE='DW_INTERACTIVE_WH'
  DEFAULT_ROLE='SCHEMACHANGE_TEAM1'
;

GRANT ROLE SCHEMACHANGE_TEAM1 TO USER SCHEMACHANGETEAM1;

DROP USER SCHEMACHANGETEAM2;
CREATE USER SCHEMACHANGETEAM2
  PASSWORD='R7.zYhPHg.cPikDeUzF3Rnwo'
  LOGIN_NAME='schemachangeteam2'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE='DW_INTERACTIVE_WH'
  DEFAULT_ROLE='SCHEMACHANGE_TEAM2'
;

GRANT ROLE SCHEMACHANGE_TEAM2 TO USER SCHEMACHANGETEAM2;

DROP USER SCHEMACHANGEDEV;
CREATE USER SCHEMACHANGEDEV
  PASSWORD='CgFmpkK9PVMXx!GGUQW3.vVc'
  LOGIN_NAME='schemachangedev'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE='DW_INTERACTIVE_WH'
  DEFAULT_ROLE='SCHEMACHANGE_DEV'
;

GRANT ROLE SCHEMACHANGE_DEV TO USER SCHEMACHANGEDEV;

